graceful:
  shutdown.enabled: false

sqs:
  endpoint.url: http://localhost:4576

oauth:
  endpoint.url: http://localhost:9090/auth

casenotes:
  endpoint.url: http://localhost:8083

delius:
  endpoint.url: http://localhost:8096/delius
