graceful:
  shutdown.enabled: false

sqs:
  provider: localstack
  endpoint:
    url: http://localhost:4576
    region: eu-west-2

oauth:
  endpoint.url: http://localhost:9090/auth

casenotes:
  endpoint.url: http://localhost:8083

delius:
  endpoint.url: http://localhost:8096/delius
